version: "3.9"

x-aws-vpc: ${VPC}
x-aws-cluster: ${CLUSTER}
x-aws-loadbalancer: ${LOAD_BALANCER}

services:
  user-microservice:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/user-microservice-jd:latest
    ports:
      - target: ${PORT_USER}
        x-aws-protocol: http
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PORT
      - MYSQL_HOST
      - ENCRYPT_SECRET_KEY
      - JWT_SECRET_KEY
    environment:
      - APP_PORT=${PORT_USER}
      - WAIT_TIME=${WAIT_TIME}
    deploy:
      resources:
        reservations:
          memory: 1Gb
          cpus: "1"
secrets:
  MYSQL_USER:
    name: ${ARN_MYSQL_USER}
    external: true
  MYSQL_PASSWORD:
    name: ${ARN_MYSQL_PASSWORD}
    external: true
  MYSQL_DATABASE:
    name: ${ARN_MYSQL_DATABASE}
    external: true
  MYSQL_PORT:
    name: ${ARN_MYSQL_PORT}
    external: true
  MYSQL_HOST:
    name: ${ARN_MYSQL_HOST}
    external: true
  ENCRYPT_SECRET_KEY:
    name: ${ARN_ENCRYPT_SECRET_KEY}
    external: true
  JWT_SECRET_KEY:
    name: ${ARN_JWT_SECRET_KEY}
    external: true

x-aws-cloudformation:
  Resources:
    UsermicroserviceService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${SUBNET_ONE}
              - ${SUBNET_TWO}
    Usermicroservice8070TargetGroup:
      Properties:
        HealthCheckPath: /health
        Matcher:
          HttpCode: 200-499